# Site
title:              Formal Verification at Utah
bio:                'This is a research page for publications and software created under Prof. Ganesh Gopalakrishnan’s guidance.'
description:        "This is a research page for publications and software created under Prof. Ganesh Gopalakrishnan’s guidance."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "./blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Salt Lake City, UT
phone:              (801) 581-8224
#email:              info@default.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-maps
  - jekyll-scholar

paginate: 6
paginate_path: "./blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, scripts, par_site_tar.gz, fv_site_tar.gz, update_log.txt]


maps:
  google:
      api_key: AIzaSyCUws1pOq7EnOvKS3niZxdzi3gVQajQhws

scholar:
  style: chicago-annotated-bibliography
  sort_by: year, month
  order: descending
  group_by: year
  group_order: descending
  bibliography_template: {{reference}}